# Define compose version 
version: "3"

# We define two services, meaning that we will ahve two running containers
# Describe our container 
services:  
  flask:  
    build: ./flask # Build the Dockerfile inside the flask folder
    container_name: flask # and five a name to the container
    restart: always # If something bad happens, restart the container
    expose: # We will need to expose port 8080 as uwsgi is listeningn on this port
      - 8080


  nginx:
    # Build the Docker file inside nginx folder
    build: ./nginx 
    container_name: nginx
    restart: always
    # We map port 80 on our local machine to port 
    ports:
      - "80:80"      
